sudo: required
services:
  - docker

before_install:
  - docker build -t yosuke0517/system-trade-frontend -f Dockerfile.dev .
script:
  - docker run -e CI=true yosuke0517/system-trade-frontend yarn test